// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package queries

import ()

type MerkleProof struct {
	Root    []byte   `json:"root"`
	Address []byte   `json:"address"`
	Proof   [][]byte `json:"proof"`
}

type MerkleTree struct {
	Root      []byte   `json:"root"`
	Addresses [][]byte `json:"addresses"`
}
