// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package queries

import (
	"time"
)

type MerkleProof struct {
	Root         []byte   `json:"root"`
	Address      []byte   `json:"address"`
	Proof        [][]byte `json:"proof"`
	UnhashedLeaf []byte   `json:"unhashedLeaf"`
}

type MerkleTree struct {
	Root           []byte   `json:"root"`
	UnhashedLeaves [][]byte `json:"unhashedLeaves"`
	Ltd            []string `json:"ltd"`
	Packed         bool     `json:"packed"`
}

type Migration struct {
	Filename  string    `json:"filename"`
	Hash      string    `json:"hash"`
	AppliedAt time.Time `json:"appliedAt"`
	Index     int32     `json:"index"`
}
