// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package queries

import (
	"time"
)

type MerkleProof struct {
	Root    []byte   `json:"root"`
	Address []byte   `json:"address"`
	Proof   [][]byte `json:"proof"`
}

type MerkleTree struct {
	Root      []byte   `json:"root"`
	Addresses [][]byte `json:"addresses"`
}

type Migration struct {
	Filename  string    `json:"filename"`
	Hash      string    `json:"hash"`
	AppliedAt time.Time `json:"appliedAt"`
	Index     int32     `json:"index"`
}
